name: Data Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # 4. Run Pipeline
      - name: Run Data Pipeline
        run: java -cp target/data-processor-1.0.jar com.company.pipeline.Main

      # 5. Commit and push changes (only on main branch, not PRs)
      - name: Commit generated files
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add target/data-processor-1.0.jar output/processed-data.csv
          git diff --staged --quiet || git commit -m "Auto-update: JAR and processed data [skip ci]"
          git push