name: Data Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # 4. Run Pipeline
      - name: Run Data Pipeline
        run: java -cp target/data-processor-1.0.jar com.company.pipeline.Main

      # 5. Upload build artifacts
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-processor-jar-${{ github.run_number }}
          path: target/data-processor-1.0.jar
          retention-days: 30

      # 6. Upload processed data
      - name: Upload processed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data-${{ github.run_number }}
          path: output/processed-data.csv
          retention-days: 30

      # 7. Show success message
      - name: Pipeline Summary
        run: |
          echo "✅ Pipeline completed successfully!"
          echo "📦 JAR file: target/data-processor-1.0.jar"
          echo "📊 Processed data: output/processed-data.csv"
          echo "💾 Artifacts available for download in Actions tab"